In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

In [30]:
#read in training data
train_df = pd.read_csv('train.csv', index_col='Id') #(1460, 80)

print(train_df.shape)
train_df.head()

(1460, 80)


MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

# Data Preprocessing

In [31]:
#tìm các cột là dạng numericcal
numeric_features = train_df.dtypes[train_df.dtypes != 'object'].index
numeric_features

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [32]:
# Dummy_na=True refers to a missing value being a legal eigenvalue, and
# creates an indicative feature for it
#all_features = pd.get_dummies(train_df, dummy_na=True) #(1460 rows × 332)

#standardizing
numeric_features = train_df.dtypes[train_df.dtypes != 'object'].index
#train_df[numeric_features] = train_df[numeric_features].apply( lambda x: (x - x.mean()) / (x.std()))
train_df[numeric_features] = train_df[train_df.dtypes[train_df.dtypes != 'object'].index]
# After standardizing the data all means vanish, hence we can set missing
# values to 0
train_df[numeric_features] = train_df[numeric_features].fillna(0)



all_features = pd.get_dummies(train_df, dummy_na=True) #(2919, 331)


In [33]:
all_features

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
Id                                                                            
1             60         65.0     8450            7            5       2003   
2             20         80.0     9600            6            8       1976   
3             60         68.0    11250            7            5       2001   
4             70         60.0     9550            7            5       1915   
5             60         84.0    14260            8            5       2000   
...          ...          ...      ...          ...          ...        ...   
1456          60         62.0     7917            6            5       1999   
1457          20         85.0    13175            6            6       1978   
1458          70         66.0     9042            7            9       1941   
1459          20         68.0     9717            5            6       1950   
1460          20         75.0     9937            5            6       1965   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  SaleType_Oth  \
Id                                                      ...                 
1             2003       196.0         706           0  ...             0   
2             1976         0.0         978           0  ...             0   
3             2002       162.0         486           0  ...             0   
4             1970         0.0         216           0  ...             0   
5             2000       350.0         655           0  ...             0   
...            ...         ...         ...         ...  ...           ...   
1456          2000         0.0           0           0  ...             0   
1457          1988       119.0         790         163  ...             0   
1458          2006         0.0         275           0  ...             0   
1459          1996         0.0          49        1029  ...             0   
1460          1965         0.0         830         290  ...             0   

      SaleType_WD  SaleType_nan  SaleCondition_Abnorml  SaleCondition_AdjLand  \
Id                                                                              
1               1             0                      0                      0   
2               1             0                      0                      0   
3               1             0                      0                      0   
4               1             0                      1                      0   
5               1             0                      0                      0   
...           ...           ...                    ...                    ...   
1456            1             0                      0                      0   
1457            1             0                      0                      0   
1458            1             0                      0                      0   
1459            1             0                      0                      0   
1460            1             0                      0                      0   

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
Id                                                                       
1                        0                     0                     1   
2                        0                     0                     1   
3                        0                     0                     1   
4                        0                     0                     0   
5                        0                     0                     1   
...                    ...                   ...                   ...   
1456                     0                     0                     1   
1457                     0                     0                     1   
1458                     0                     0                     1   
1459                     0                     0                     1   
1460                     0        

In [34]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
# Scale both the training inputs and outputs
scaled_train = scaler.fit_transform(all_features)
scaled_train


array([[0.23529412, 0.20766773, 0.0334198 , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.25559105, 0.03879502, ..., 1.        , 0.        ,
        0.        ],
       [0.23529412, 0.2172524 , 0.04650728, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.29411765, 0.21086262, 0.03618687, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.2172524 , 0.03934189, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.23961661, 0.04037019, ..., 1.        , 0.        ,
        0.        ]])

In [35]:
# Print out the adjustment that the scaler applied to the total_earnings column of data
num_of_features = all_features.shape[1] - 1
print('num_of_features: {}'.format(num_of_features))
print("Note: median values were scaled by multiplying by {:.10f} and adding {:.6f}".format(scaler.scale_[num_of_features], scaler.min_[num_of_features]))
multiplied_by = scaler.scale_[num_of_features]
added = scaler.min_[num_of_features]


num_of_features: 331
Note: median values were scaled by multiplying by 1.0000000000 and adding 0.000000


In [37]:
#scaled_train_df = pd.DataFrame(scaled_train, columns=all_features.columns.values) #1460 rows × 332 columns
scaled_train_df = pd.DataFrame(scaled_train, columns=all_features.columns.values)
scaled_train_df.SalePrice

0       0.241078
1       0.203583
2       0.261908
3       0.145952
4       0.298709
          ...   
1455    0.194556
1456    0.243161
1457    0.321622
1458    0.148903
1459    0.156367
Name: SalePrice, Length: 1460, dtype: float64

# Let't build our tf.keras model

In [38]:
model = tf.keras.Sequential()

In [62]:
#model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))
#model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(1))

In [63]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [64]:
X = scaled_train_df.drop('SalePrice', axis=1).values
Y = scaled_train_df[['SalePrice']].values
Y

array([[0.24107763],
       [0.20358284],
       [0.26190807],
       ...,
       [0.321622  ],
       [0.14890293],
       [0.15636717]])

In [65]:
# Train the model
model.fit(
    X[10:],
    Y[10:],
    epochs=50,
    shuffle=True,
    verbose=0
)

In [66]:
test_error_rate = model.evaluate(X[:10], Y[:10], verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

The mean squared error (MSE) for the test data set is: 0.0020575174130499363


In [67]:
prediction = model.predict(X[:10])
prediction

array([[0.26151428],
       [0.19538392],
       [0.26238778],
       [0.22109698],
       [0.33843753],
       [0.18056278],
       [0.27665982],
       [0.2677707 ],
       [0.11908894],
       [0.12239195]], dtype=float32)

In [68]:
Y[:10]

array([[0.24107763],
       [0.20358284],
       [0.26190807],
       [0.14595195],
       [0.29870851],
       [0.15011804],
       [0.37786419],
       [0.22927371],
       [0.13192612],
       [0.11540064]])

In [69]:
def rev_min_max_func(scaled_val):
    max_val = max(all_features['SalePrice'])
    min_val = min(all_features['SalePrice'])
    og_val = (scaled_val*(max_val - min_val)) + min_val
    return og_val

In [70]:
Y_original = rev_min_max_func(Y[:10])
Y_original

array([[208500.],
       [181500.],
       [223500.],
       [140000.],
       [250000.],
       [143000.],
       [307000.],
       [200000.],
       [129900.],
       [118000.]])

In [71]:
#Y_1 = rev_min_max_func(y_0) #scaled_labeled_df['pred_scaled_target'].apply(lambda x: rev_min_max_func(x))
Y_1 = rev_min_max_func(prediction)

In [72]:
Y_1

array([[223216.43033922],
       [175595.96170336],
       [223845.44205964],
       [194111.93356365],
       [278608.8634938 ],
       [164923.25737923],
       [234122.73386419],
       [227721.68654799],
       [120655.94592616],
       [123034.44075659]])

# House Prices Predict by Tensor-flow

In [246]:
train_df = pd.read_csv('train.csv') #(1460, 81)
test_df =  pd.read_csv('test.csv')
all_df = pd.concat((train_df.iloc[:, 1:-1], test_df.iloc[:, 1:])) #2919 rows × 79 columns (remove SalePrice)
#all_features #2919, 79


print(train_df.shape)
print(test_df.shape)
print(all_df.shape)
all_df.head()

(1460, 81)
(1459, 80)
(2919, 79)


MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          60       RL         65.0     8450   Pave   NaN      Reg   
1          20       RL         80.0     9600   Pave   NaN      Reg   
2          60       RL         68.0    11250   Pave   NaN      IR1   
3          70       RL         60.0     9550   Pave   NaN      IR1   
4          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC Fence  \
0         Lvl    AllPub    Inside  ...           0        0    NaN   NaN   
1         Lvl    AllPub       FR2  ...           0        0    NaN   NaN   
2         Lvl    AllPub    Inside  ...           0        0    NaN   NaN   
3         Lvl    AllPub    Corner  ...           0        0    NaN   NaN   
4         Lvl    AllPub       FR2  ...           0        0    NaN   NaN   

  MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0       2    2008        WD         Normal  
1         NaN       0       5    2007        WD         Normal  
2         NaN       0       9    2008        WD         Normal  
3         NaN       0       2    2006        WD        Abnorml  
4         NaN       0      12    2008        WD         Normal  

[5 rows x 79 columns]

# Data Preprocessing

In [248]:
#standardizing
numeric_features = all_df.dtypes[train_df.dtypes != 'object'].index
# After standardizing the data all means vanish, hence we can set missing
# values to 0
all_df[numeric_features] = all_df[numeric_features].fillna(0)

#encode others
all_features = pd.get_dummies(all_df, dummy_na=True) #(2919, 331)


all_features

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0             60         65.0     8450            7            5       2003   
1             20         80.0     9600            6            8       1976   
2             60         68.0    11250            7            5       2001   
3             70         60.0     9550            7            5       1915   
4             60         84.0    14260            8            5       2000   
...          ...          ...      ...          ...          ...        ...   
1454         160         21.0     1936            4            7       1970   
1455         160         21.0     1894            4            5       1970   
1456          20        160.0    20000            5            7       1960   
1457          85         62.0    10441            5            5       1992   
1458          60         74.0     9627            7            5       1993   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  SaleType_Oth  \
0             2003       196.0       706.0         0.0  ...             0   
1             1976         0.0       978.0         0.0  ...             0   
2             2002       162.0       486.0         0.0  ...             0   
3             1970         0.0       216.0         0.0  ...             0   
4             2000       350.0       655.0         0.0  ...             0   
...            ...         ...         ...         ...  ...           ...   
1454          1970         0.0         0.0         0.0  ...             0   
1455          1970         0.0       252.0         0.0  ...             0   
1456          1996         0.0      1224.0         0.0  ...             0   
1457          1992         0.0       337.0         0.0  ...             0   
1458          1994        94.0       758.0         0.0  ...             0   

      SaleType_WD  SaleType_nan  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0               1             0                      0                      0   
1               1             0                      0                      0   
2               1             0                      0                      0   
3               1             0                      1                      0   
4               1             0                      0                      0   
...           ...           ...                    ...                    ...   
1454            1             0                      0                      0   
1455            1             0                      1                      0   
1456            1             0                      1                      0   
1457            1             0                      0                      0   
1458            1             0                      0                      0   

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                        0                     0                     1   
1                        0                     0                     1   
2                        0                     0                     1   
3                        0                     0                     0   
4                        0                     0                     1   
...                    ...                   ...                   ...   
1454                     0                     0                     1   
1455                     0                     0                     0   
1456                     0                     0                     0   
1457                     0                     0                     1   
1458                     0                     0                     1   

      SaleCondition_Partial  SaleCondition_nan  
0                         0                  0  
1                         0                  0  
2                         0                  0  
3                         0                  0  
4                        

In [251]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
# Scale both the training inputs
scaled_data_x = scaler.fit_transform(all_features)
scaled_train_y = scaler.fit_transform(train_df[['SalePrice']])

In [252]:
scaled_data_x_df = pd.DataFrame(scaled_data_x, columns=all_features.columns.values)
scaled_data_x_df

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  YearBuilt  \
0       0.235294     0.207668  0.033420     0.666667        0.500   0.949275   
1       0.000000     0.255591  0.038795     0.555556        0.875   0.753623   
2       0.235294     0.217252  0.046507     0.666667        0.500   0.934783   
3       0.294118     0.191693  0.038561     0.666667        0.500   0.311594   
4       0.235294     0.268371  0.060576     0.777778        0.500   0.927536   
...          ...          ...       ...          ...          ...        ...   
2914    0.823529     0.067093  0.002973     0.333333        0.750   0.710145   
2915    0.823529     0.067093  0.002776     0.333333        0.500   0.710145   
2916    0.000000     0.511182  0.087406     0.444444        0.750   0.637681   
2917    0.382353     0.198083  0.042726     0.444444        0.500   0.869565   
2918    0.235294     0.236422  0.038921     0.666667        0.500   0.876812   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  SaleType_Oth  \
0         0.883333     0.12250    0.125089         0.0  ...           0.0   
1         0.433333     0.00000    0.173281         0.0  ...           0.0   
2         0.866667     0.10125    0.086109         0.0  ...           0.0   
3         0.333333     0.00000    0.038271         0.0  ...           0.0   
4         0.833333     0.21875    0.116052         0.0  ...           0.0   
...            ...         ...         ...         ...  ...           ...   
2914      0.333333     0.00000    0.000000         0.0  ...           0.0   
2915      0.333333     0.00000    0.044649         0.0  ...           0.0   
2916      0.766667     0.00000    0.216867         0.0  ...           0.0   
2917      0.700000     0.00000    0.059709         0.0  ...           0.0   
2918      0.733333     0.05875    0.134302         0.0  ...           0.0   

      SaleType_WD  SaleType_nan  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0             1.0           0.0                    0.0                    0.0   
1             1.0           0.0                    0.0                    0.0   
2             1.0           0.0                    0.0                    0.0   
3             1.0           0.0                    1.0                    0.0   
4             1.0           0.0                    0.0                    0.0   
...           ...           ...                    ...                    ...   
2914          1.0           0.0                    0.0                    0.0   
2915          1.0           0.0                    1.0                    0.0   
2916          1.0           0.0                    1.0                    0.0   
2917          1.0           0.0                    0.0                    0.0   
2918          1.0           0.0                    0.0                    0.0   

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                      0.0                   0.0                   1.0   
1                      0.0                   0.0                   1.0   
2                      0.0                   0.0                   1.0   
3                      0.0                   0.0                   0.0   
4                      0.0                   0.0                   1.0   
...                    ...                   ...                   ...   
2914                   0.0                   0.0                   1.0   
2915                   0.0                   0.0                   0.0   
2916                   0.0                   0.0                   0.0   
2917                   0.0                   0.0                   1.0   
2918                   0.0                   0.0                   1.0   

      SaleCondition_Partial  SaleCondition_nan  
0                       0.0                0.0  
1                       0.0                0.0  
2                       0.0                0.0  
3                       0.0                0.0  
4            

# build our tf.keras model

In [255]:
model = tf.keras.Sequential()

#
model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(1))

#
model.compile(loss='mean_squared_error', optimizer='adam')


In [259]:
X_train_and_test = scaled_data_x_df.values

#
X_train = X_train_and_test[:1460]
Y_train = scaled_train_y

X_test = X_train_and_test[1460:]

In [260]:
# Train the model
model.fit(
    X_train,
    Y_train,
    epochs=50,
    shuffle=True,
    verbose=0
)

In [261]:

test_error_rate = model.evaluate(X_train, Y_train, verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

The mean squared error (MSE) for the test data set is: 0.0001286314509343356


In [262]:
prediction = model.predict(X_test)
print(prediction.shape)
prediction

(1459, 1)


array([[0.13978627],
       [0.19275951],
       [0.23011222],
       ...,
       [0.17003387],
       [0.1349048 ],
       [0.24754754]], dtype=float32)

In [263]:
def rev_min_max_func(scaled_val):
    max_val = max(train_df['SalePrice'])
    min_val = min(train_df['SalePrice'])
    og_val = (scaled_val*(max_val - min_val)) + min_val
    return og_val

In [264]:
Y_test = rev_min_max_func(prediction)
print(Y_test.shape)
Y_test


(1459, 1)


array([[135560.09536088],
       [173706.12592697],
       [200603.81309092],
       ...,
       [157341.39131904],
       [132044.94780898],
       [213158.98145735]])

In [266]:
test_df['SalePrice'] = Y_test
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition      SalePrice  
0         6   2010        WD         Normal  135560.095361  
1         6   2010        WD         Normal  173706.125927  
2         3   2010        WD         Normal  200603.813091  
3         6   2010        WD         Normal  215348.053840  
4         1   2010        WD         Normal  185120.510396  
...     ...    ...       ...            ...            ...  
1454      6   2006        WD         Normal   88580.999781  
1455      4   2006        WD        Abnorml   88652.490579  
1456      9   2006        WD        Abnorml  157341.391319  
1457      7   2006        WD         Normal  132044.947809  
1458     11   2006        WD         Normal  213158.981457  

[1459 rows x 81 columns]

In [272]:
summit =  test_df[['Id', 'SalePrice']].set_index('Id')
summit

SalePrice
Id                 
1461  135560.095361
1462  173706.125927
1463  200603.813091
1464  215348.053840
1465  185120.510396
...             ...
2915   88580.999781
2916   88652.490579
2917  157341.391319
2918  132044.947809
2919  213158.981457

[1459 rows x 1 columns]

In [273]:
summit.to_csv('HousePrice_TheDung_Try_2nd')