https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

In [12]:
import numpy as np

In [4]:
#2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']


In [33]:
#3. Create a null vector of size 10 
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
#4. How to find the memory size of any array (★☆☆)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


In [35]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
Z = np.zeros(10)
Z[4] = 1
print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [36]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
Z = np.arange(10,50)
print(Z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [40]:
#8. Reverse a vector (first element becomes last) (★☆☆)
Z = np.arange(50)
Z = Z[::-1]
print(Z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [41]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [42]:
#11. Create a 3x3 identity matrix -- Ma trận đơn vị (★☆☆)
Z = np.eye(3)
print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#12. Create a 3x3x3 array with random values (★☆☆)
Z = np.random.random((3,3,3))
print(Z)


[[[0.18998255 0.91239242 0.16225535]
  [0.7901998  0.74892528 0.26714534]
  [0.1148022  0.57690369 0.17112274]]

 [[0.80202784 0.44333663 0.99035708]
  [0.0584617  0.53696229 0.57284671]
  [0.60650775 0.11594481 0.85016466]]

 [[0.10827917 0.81785485 0.33313411]
  [0.11835878 0.53699127 0.13661416]
  [0.03061074 0.96980766 0.60424896]]]


In [47]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


0.0028357028299937914 0.998876884563227


In [55]:
#http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.average.html
#14. Create a random vector of size 30 and find the mean value (★☆☆) -- Tính trung bình
Z = np.random.random(30)
m = Z.mean()
print(m)

#----------------------------------------
data = np.arange(6).reshape((3,2))
print(data)
m = data.mean()
m = data.mean(axis = 0)
print(m)
#----------------------------------------
m = np.average(data)
m = np.average(data, axis = 0)
print(m)

0.4490586769758024
[[0 1]
 [2 3]
 [4 5]]
[2. 3.]
[2. 3.]


In [59]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Z = np.ones((10,10))
print(Z)
Z[1:-1,1:-1] = 0
print('---------------------------------------------')
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
---------------------------------------------
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [61]:
#http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.pad.html
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Z = np.ones((5,5))
print(Z)
print('---------------------------------------------')
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
---------------------------------------------
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


2.	Write a python script to get a number N from user then create 3D array N x N x N with random (float) values on interval [0,10].
○	 Find min, max and sum of array by 3 axis (i.e., deep, height and width).


In [50]:
N = int(input("Please enter a N:\n"))
if (isinstance(N, int)):
    print('create matrix ({},{},{}) random (0,10.0):'.format(N, N, N))
else:
    N = 1
#-------------------------------------------------    
a = np.random.random_sample((N, N, N))* 10.0
a

Please enter a N:
3
create matrix (3,3,3) random (0,10.0):


array([[[2.94957178, 2.17407561, 7.9049494 ],
        [5.41630691, 4.18799792, 4.7649907 ],
        [5.65772972, 8.49398264, 6.60126818]],

       [[4.65263923, 2.64455758, 4.33369684],
        [8.15682191, 8.48616467, 1.18501331],
        [4.58813767, 4.04966091, 8.00912318]],

       [[9.94349388, 4.06050489, 0.26490136],
        [4.13600075, 9.74688443, 7.83124496],
        [2.5987969 , 4.63401319, 7.58259276]]])

In [58]:
print('Min is:{} , Max is {}, Sum is {}'.format(a.min(), a.max(), a.sum()))

Min is:0.2649013583902782 , Max is 9.943493882636771, Sum is 145.0551213056908


In [64]:
axis = int(input("Please enter a Axis from 0, 1, 2:\n"))
if (isinstance(N, int) and axis <= 2):
    print('Min Aixs[{}] is {} '.format(axis, a.min(axis)))
    print('--------------------------------')
    print('Max Aixs[{}] is {} '.format(axis, a.max(axis)))
    print('--------------------------------')
    print('Sum Aixs[{}] is {} '.format(axis, a.sum(axis)))

Please enter a Axis from 0, 1, 2:
1
Min Aixs[1] is [[2.94957178 2.17407561 4.7649907 ]
 [4.58813767 2.64455758 1.18501331]
 [2.5987969  4.06050489 0.26490136]] 
--------------------------------
Max Aixs[1] is [[5.65772972 8.49398264 7.9049494 ]
 [8.15682191 8.48616467 8.00912318]
 [9.94349388 9.74688443 7.83124496]] 
--------------------------------
Sum Aixs[1] is [[14.02360841 14.85605616 19.27120829]
 [17.39759882 15.18038316 13.52783334]
 [16.67829153 18.44140251 15.67873908]] 


3.	Write a python script to get three number M, N and K from user then create 3D array M x N x K with random integer numbers on interval [-100,100].
○	 Find min, max and sum of array by 3 axis (i.e., deep, height and width).


In [66]:
M = int(input("Please enter a M as int :\n"))
N = int(input("Please enter a N as int :\n"))
K = int(input("Please enter a K as int :\n"))

Please enter a M:
3
Please enter a N:
4
Please enter a K:
5


In [67]:
a = np.random.randint(-100, 1000, size=(M, N, K))
a

array([[[ -3, -34, 915,  -2, 398],
        [252, 903, 273, 965, 799],
        [317, 352, 502, 536, 625],
        [450, 160, 526, 633, 526]],

       [[862, 943, 866,  89, 138],
        [942, 833, 427, 358, 873],
        [165, -41, 681, 683, 326],
        [902, -48, 308, 802, 337]],

       [[773,  21,  -6, 629, 404],
        [-51, 982, 962, 180, 603],
        [613, 443, -75, 475, 687],
        [142, 485, 515,  92, 190]]])

In [68]:
print('Min is:{} , Max is {}, Sum is {}'.format(a.min(), a.max(), a.sum()))

Min is:-75 , Max is 982, Sum is 27603


In [69]:
axis = int(input("Please enter a Axis from 0, 1, 2:\n"))
if (isinstance(N, int) and axis <= 2):
    print('Min Aixs[{}] is {} '.format(axis, a.min(axis)))
    print('--------------------------------')
    print('Max Aixs[{}] is {} '.format(axis, a.max(axis)))
    print('--------------------------------')
    print('Sum Aixs[{}] is {} '.format(axis, a.sum(axis)))

Please enter a Axis from 0, 1, 2:
0
Min Aixs[0] is [[ -3 -34  -6  -2 138]
 [-51 833 273 180 603]
 [165 -41 -75 475 326]
 [142 -48 308  92 190]] 
--------------------------------
Max Aixs[0] is [[862 943 915 629 404]
 [942 982 962 965 873]
 [613 443 681 683 687]
 [902 485 526 802 526]] 
--------------------------------
Sum Aixs[0] is [[1632  930 1775  716  940]
 [1143 2718 1662 1503 2275]
 [1095  754 1108 1694 1638]
 [1494  597 1349 1527 1053]] 


4.	Write a python script to randomly generate a 2D array 10 x 8 of float values on interval [-10, 10].
○	And then, get a float number from user and find its closest values in the array. SOME GUIDES: 
i.	i) use argmin() function for your problem: https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html;
ii.	Or reshape to 1D, subtract array to value and sort. 
○	Optional: If you passed the above problem, extend it to find 3 closest values in the array.


In [95]:
a = (-10) + np.random.random_sample((10, 8))* 20.0
a

array([[-5.33725155, -6.62785249, -0.33266491, -6.61672692, -3.13340662,
        -8.09346338, -4.55326562,  3.65270283],
       [-3.52409018,  0.79669499,  0.22855837,  5.30546243, -2.22484843,
        -4.37375008,  3.87399827, -5.6111706 ],
       [-0.42925525, -9.30682469, -0.96333035, -2.8187609 , -9.68948886,
        -5.91161144,  6.8606505 ,  3.71763517],
       [ 8.55495974, -7.09025592,  5.56031633, -2.12875303, -9.03520984,
        -8.22215557,  9.65834068, -3.01560622],
       [ 0.16327897,  2.73131649,  1.0593631 , -2.23363908,  8.08812432,
         4.95471936,  8.81494115,  7.7375727 ],
       [-8.17215598,  2.40771667,  3.87124761,  3.66083318,  9.08901878,
        -3.85672978, -5.95039134, -7.37426206],
       [ 7.22514306,  7.09661832, -9.56141397, -2.95352573,  5.98840674,
         0.9444093 , -9.52586164,  1.5238576 ],
       [-2.35124561, -0.50172513, -7.02638604, -2.49051104, -5.90895637,
         5.53859908,  2.49116536,  2.78696154],
       [ 3.37079888,  5.62639522

In [108]:
b = float(input("Please enter a float value:"))
#
if (isinstance(b, float)):
    c = np.argmin(a[a>=b])  # Only the first occurrence is returned.
    print('the close value with {} is at index {}, value is {}'.format(b, c, m[c]))

Please enter a float value:8
the close value with 8.0 is at index 2, value is 8.737743444323584


In [110]:
if (isinstance(b, float)):
    m = np.sort(a[a>=b], axis=None)     # sort the flattened array
    c = m[0:3]
    print('the 3 closetvalue with {} is {}'.format(b, c, c))  

the 3 closetvalue with 8.0 is [8.08812432 8.55495974 8.73774344]


5.	Read the following financial function to more understand about numpy: https://docs.scipy.org/doc/numpy/reference/routines.financial.html. For each function, give a example and try it.

B.	ADDITIONAL PART

1.	Download iris data set from here https://archive.ics.uci.edu/ml/datasets/iris, and save it to a file.
a.	Load data of the downloaded file into a 2D array of numbers where 3 types of flowers is mapped to vector (1 = Setosa, 2=Versicolour, 3=Virginica). 
GUIDE: use loadtxt() or genfromtxt() to load file content into a list of tuple, then run for loop to convert list of tuple to 1D array, then reshape it to 2D. While converting, map name of flower to number.   
b.	Calculate 3 covariance matrix of sepal length and sepal width for each type of flower. (see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html )


In [121]:
def from_txt_to_iris_class(x):
    if x == b'Iris-setosa': 
        return 1
    elif x == b'Iris-versicolor': 
        return 2
    elif x == b'Iris-virginica': 
        return 3
    else:
        return np.nam

In [122]:
a = np.loadtxt('iris.data',delimiter=',', converters ={4: from_txt_to_iris_class}) 
a

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [120]:
np.shape(a)

(150, 5)

b.	Calculate 3 covariance matrix of sepal length and sepal width for each type of flower. (see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html )
. covariance matrix ==> Ma trận hiệp phương
https://minhng.info/toan-hoc/ma-tran-hiep-phuong-sai-covariance-matrix.html

In [123]:
b = np.cov(a)
b

array([[4.043 , 3.7425, 3.6835, ..., 2.5505, 2.267 , 2.2445],
       [3.7425, 3.49  , 3.4125, ..., 2.54  , 2.2425, 2.2325],
       [3.6835, 3.4125, 3.357 , ..., 2.3335, 2.069 , 2.054 ],
       ...,
       [2.5505, 2.54  , 2.3335, ..., 3.418 , 3.0495, 3.0995],
       [2.267 , 2.2425, 2.069 , ..., 3.0495, 2.758 , 2.783 ],
       [2.2445, 2.2325, 2.054 , ..., 3.0995, 2.783 , 2.843 ]])

In [124]:
np.shape(b)

(150, 150)